### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by caitken-com** [jxu/vector.js#1]
```js
let a = new Vector([150, 150, 150]);
let b = new Vector([200, 200, 0]);
let c = a.add(b);
```
Console:
```
Assertion failed: Vector constructor expected Array, got 3
Uncaught TypeError: Found non-callable @@iterator at new Vector (Vector.js:18:4)
```
The map function within `Vector.add` isn't returning an array?

Tried in Chrome 98, Safari 15 and Firefox 97.

**Comment by jxu** [comment]
Hm, I haven't looked at this test code in a while. Did you find it through StackOverflow? 

This probably messed up somewhere when I changed how Vector's constructor worked. I'm still not happy with it and I will probably revert it to be just like Array's constructor since I assume [`Array.prototype.map()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) uses [`Array.prototype.[@@iterator]()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/@@iterator) as constructor (I'm still a js beginner). Maybe for fun I'll make alpha release version numbering.

**Comment by aitken85** [comment]
Yes, I found it via StackOverflow! But I don't have enough points or something to post on SO.

I ended up removing the custom constructor and just inheriting the array's constructor. Works beautifully now.

**Comment by caitken-com** [comment]
Yes, I found it via StackOverflow! But I don't have enough points or something to post on SO.

I ended up removing the custom constructor and just inheriting the array's constructor. Works beautifully now.
